release/v1.0.13: Increase max trace logs per span in Alpha. (#3806)
* Increase max trace logs per span in Alpha. (#3679)

Bump up the number of logs per span to capture all the events
from Server.Query which can create a lot of logs.

* Vendor in external dependencies necessary for OpenCensus.

We did not strictly vendor everything when v1.0.13 was originally released. Now
that we need to create a new patch release on top of Dgraph v1.0.13, we need to
bring back old dependencies that are necessary to create a new Dgraph binary. We
pick up versions for OpenCensus, Prometheus client, and gRPC that were released
before March 10, 2019 (the v1.0.13 release date).

* OpenCensus

  govendor fetch go.opencensus.io/...@v0.19.2

  v0.19.2 was released on Mar 21, 2019.

  I tried vendoring in v1.19.1 (released Mar 4) but it won't succeed with this
  error. v0.19.2 should be ok to use.

    Error: repo remote not secure
    Failed to fetch package "git.apache.org/thrift.git/lib/go/thrift"

* Prometheus client

  govendor fetch github.com/prometheus/client_golang/prometheus/...@v0.9.2

  v0.9.2 was released on Dec 6, 2018.

* gRPC

  govendor fetch google.golang.org/grpc/...@v1.13.0

  v1.13.0 was released on Jun 19, 2018.

  We already version lock gRPC to v1.13.0 in the contrib/release.sh.

(cherry picked from commit b196ca3164e65714135d2949bb28b0d9c72c4482)