Add a test for the existence of a required file
Seeing this issue occasionally

=== RUN   TestLoaderXidmap
    client.go:222:
        	Error Trace:	/home/runner/work/dgraph/dgraph/testutil/client.go:222
        	            				/home/runner/work/dgraph/dgraph/systest/loader/loader_test.go:49
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unavailable desc = connection error: desc = "error reading server preface: remote error: tls: certificate required"
        	Test:       	TestLoaderXidmap
--- FAIL: TestLoaderXidmap (0.01s)