hack: Run schema queries to see why queries fail.
In the output below:

1. Live loader runs with family.schema which includes indexes.
2. The schema says that the name predicate does not have any index
3. The query runs, expecting a term index.

pipeline: [[/home/dmai/go/bin/dgraph live --schema /home/dmai/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/load-uids/family.schema --files /home/dmai/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/load-uids/family.json --alpha localhost:33616 --zero localhost:33567 -u groot -p password]]
[Decoder]: Using assembly version of decoder
Page Size: 4096
Running transaction with dgraph endpoint: localhost:33616
Login successful.
Processing schema file "/home/dmai/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/load-uids/family.schema"
Processed schema file "/home/dmai/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/load-uids/family.schema"
Found 1 data file(s) to process
Processing data file "/home/dmai/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/live/load-uids/family.json"
Number of TXs run            : 1
Number of N-Quads processed  : 43
Time spent                   : 67.855766ms
N-Quads processed per second : 43
json:"{\"schema\":[{\"predicate\":\"age\",\"type\":\"int\"},{\"predicate\":\"aka\",\"type\":\"string\"},{\"predicate\":\"carries\",\"type\":\"string\"},{\"predicate\":\"dgraph.acl.rule\",\"type\":\"uid\",\"list\":true},{\"predicate\":\"dgraph.cors\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"],\"list\":true,\"upsert\":true},{\"predicate\":\"dgraph.drop.op\",\"type\":\"string\"},{\"predicate\":\"dgraph.graphql.p_query\",\"type\":\"string\"},{\"predicate\":\"dgraph.graphql.p_sha256hash\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"]},{\"predicate\":\"dgraph.graphql.schema\",\"type\":\"string\"},{\"predicate\":\"dgraph.graphql.schema_created_at\",\"type\":\"datetime\"},{\"predicate\":\"dgraph.graphql.schema_history\",\"type\":\"string\"},{\"predicate\":\"dgraph.graphql.xid\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"],\"upsert\":true},{\"predicate\":\"dgraph.password\",\"type\":\"password\"},{\"predicate\":\"dgraph.rule.permission\",\"type\":\"int\"},{\"predicate\":\"dgraph.rule.predicate\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"],\"upsert\":true},{\"predicate\":\"dgraph.type\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"],\"list\":true},{\"predicate\":\"dgraph.user.group\",\"type\":\"uid\",\"reverse\":true,\"list\":true},{\"predicate\":\"dgraph.xid\",\"type\":\"string\",\"index\":true,\"tokenizer\":[\"exact\"],\"upsert\":true},{\"predicate\":\"name\",\"type\":\"string\"},{\"predicate\":\"parent_to\",\"type\":\"uid\",\"list\":true},{\"predicate\":\"role\",\"type\":\"string\"},{\"predicate\":\"sibling_of\",\"type\":\"uid\",\"list\":true}],\"types\":[{\"fields\":[{\"name\":\"name\"},{\"name\":\"age\"},{\"name\":\"role\"},{\"name\":\"aka\"},{\"name\":\"carries\"},{\"name\":\"parent_to\"},{\"name\":\"sibling_of\"}],\"name\":\"FamilyMember\"},{\"fields\":[{\"name\":\"dgraph.graphql.schema\"},{\"name\":\"dgraph.graphql.xid\"}],\"name\":\"dgraph.graphql\"},{\"fields\":[{\"name\":\"dgraph.graphql.schema_history\"},{\"name\":\"dgraph.graphql.schema_created_at\"}],\"name\":\"dgraph.graphql.history\"},{\"fields\":[{\"name\":\"dgraph.graphql.p_query\"},{\"name\":\"dgraph.graphql.p_sha256hash\"}],\"name\":\"dgraph.graphql.persisted_query\"},{\"fields\":[{\"name\":\"dgraph.xid\"},{\"name\":\"dgraph.acl.rule\"}],\"name\":\"dgraph.type.Group\"},{\"fields\":[{\"name\":\"dgraph.rule.predicate\"},{\"name\":\"dgraph.rule.permission\"}],\"name\":\"dgraph.type.Rule\"},{\"fields\":[{\"name\":\"dgraph.xid\"},{\"name\":\"dgraph.password\"},{\"name\":\"dgraph.user.group\"}],\"name\":\"dgraph.type.User\"}]}" txn:<start_ts:1473 > latency:<parsing_ns:13688 processing_ns:742728 assign_timestamp_ns:655815 total_ns:1836730 > metrics:<num_uids:<key:"_total" value:0 > >
    load_test.go:146:
            Error Trace:    load_test.go:146
                                        load_test.go:212
            Error:          Received unexpected error:
                            rpc error: code = Unknown desc = : rpc error: code = Unknown desc = Attribute name is not indexed with type term
            Test:           TestLiveLoadJsonUidKeep