test: Fix ToHex test.
Second argument for ToHex was missing in the test.

    INFO: Running test for github.com/dgraph-io/dgraph/x
    ...
    # github.com/dgraph-io/dgraph/x [github.com/dgraph-io/dgraph/x.test]
    x/x_test.go:163:41: not enough arguments in call to ToHex
    	have (number)
    	want (uint64, bool)
    x/x_test.go:164:41: not enough arguments in call to ToHex
    	have (number)
    	want (uint64, bool)
    x/x_test.go:165:42: not enough arguments in call to ToHex
    	have (number)
    	want (uint64, bool)
    x/x_test.go:166:42: not enough arguments in call to ToHex
    FAIL	github.com/dgraph-io/dgraph/x [build failed]
    	have (number)
    	want (uint64, bool)
    x/x_test.go:167:56: not enough arguments in call to ToHex
    	have (number)
    	want (uint64, bool)