Vendor in prometheus/client_golang/prometheus v0.9.4. (#3653)
    $ govendor fetch github.com/prometheus/client_golang/prometheus/...@v0.9.4

The latest master of prometheus/client_golang/prometheus causes the following
error when building Dgraph:

    # github.com/dgraph-io/dgraph/x
    ../x/metrics.go:285:43: undefined: prometheus.Handler

v0.9.4 is the latest tagged version that works for Dgraph v1.0.

We no longer use this dependency in v1.1, so this vendored change is only
needed in release/v1.0.